### ISSUE TITLE
Source of Imgui demo.

### ISSUE THREAD

**Issue by codecnotsupported** [ddovod/jet-live#17]
Hey, I was wondering if you could post the source of your IMGUI demo.
I made my own version ( terribly hacked together ) and was wondering how you implemented it so I could learn from it.
![output](https://user-images.githubusercontent.com/2294209/52068255-99527080-257c-11e9-8b9d-affd9cadf3ab.gif)

**Comment by ddovod** [comment]
Hey! Looks nice.
Afaiu you're talking about Log widget, right?

**Comment by codecnotsupported** [comment]
> Hey! Looks nice.
> Afaiu you're talking about Log widget, right?
Yup, though the source of the start of demo would be nice too.

**Comment by ddovod** [comment]
Okay, so the framework used to create that demo is not yet ready to be exposed (at least I'm not ready to make it public), but you can try some [cocos2d-x + imgui](https://github.com/Rubonnek/cocos2d-x-imgui) repo (this is only one of them), you'll get the same experience plus a lot of info about how to work with cocos2d-x.
If you need colorized log output, please see [this comment](https://github.com/ocornut/imgui/issues/902#issuecomment-450990701) with the link to the gist with code you need. Also you need to add `-fcolor-diagnostics` compiler flag globally to the cmake to tell compiler to print colorized output.
That's all how I can help you with this. If you have any problem integrating cocos2d-x and jet-live, just open an issue, I'll try to help you.

**Comment by ddovod** [comment]
Deal. Anyway, if I can help you somehow with something, just ping me on email. Good luck!

**Comment by krumelmonster** [comment]
@codecnotsupported would you like to post your code?

**Comment by hippyau** [comment]
Hey!   This is awesome!!!!

jet-live... I love it!!  I've in just two hours hacked jet-live into a ImGui demo and it's great :)  very hacky, but it works...

I got very lost in RCCPP and gave up, so glad I found this!

So, when I press 'Reload' in the hello world window, it reloads my UI class.

![image](https://user-images.githubusercontent.com/36442309/103734320-74ec5200-5037-11eb-9afd-255bd8366724.png)


However, I have this issue where the output to the console from the logger is 'invisible' in VS code terminal - maybe because my dark theme... I have never noticed this before!   

See the grey area in the terminal is where I have selected text I can't see, copied and pasted into notepad and I can see it! 

![image](https://user-images.githubusercontent.com/36442309/103734282-600fbe80-5037-11eb-9509-c703a4855219.png)

I tried putting ANSI in the logger to set a white colour... but that didn't help.  This probs has nothing to do with jet-live, maybe it does? 

![image](https://user-images.githubusercontent.com/36442309/103734491-d57b8f00-5037-11eb-9489-b8400eb88b82.png)

I found your ANSI gist for ImGui and implemented it, but not sure how to make a logging window like yours.

Cheers,
  Hippy.

**Comment by hippyau** [comment]
It's totally my VS Code theme :)  ....  though how can I change the black text the logger is producing?

**Comment by ddovod** [comment]
Hi. I'm facing similar issues with vscode sometimes. There's nothing to do with the library, it just produces strings. You can try to add
```
    ...
    "terminal" : "integrated",
    ...
```
to your launch.json configuration. I'm on linux (xubuntu 18.04) and logs in vscode looks fine on my side
